"""Notifier protocol and in-app back-end for workflow attention
events.

Kept LLM-free and deterministic: messages are rendered from a
fixed per-status template, never generated by a model.
"""
from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass
from datetime import datetime
from typing import TYPE_CHECKING, Literal, Protocol

from app.models_workflow import WorkflowRun

if TYPE_CHECKING:
    from app.persistence.notification_store import NotificationStore
    from app.storage.notification_bus import NotificationBus

_log = logging.getLogger("kestrel.notifications")

#: Statuses that warrant a notification: the human's attention is
#: needed (any "awaiting_*" gate) or the run reached a terminal
#: outcome worth knowing about. "rejected" is excluded — the human
#: caused it themselves by rejecting with no feedback.
NOTIFY_STATUSES = frozenset({"done", "failed", "escalated"})

#: A notification's signal class (see module-notification-alarm-discipline).
#: An ``action_required`` item is a gate blocking on the human; a ``summary``
#: is a terminal, catch-up item that needs no action. The UI separates them
#: so a badge count means "things needing action", not "unread everything".
SignalClass = Literal["action_required", "summary"]


def signal_class(status: str) -> SignalClass:
    """
    Classify a notification status as action-required or summary.

    :param status: The run status the notification was raised for.
    :returns: ``"action_required"`` for an ``awaiting_*`` gate, else
        ``"summary"`` (terminal outcomes such as ``done``/``failed``).
    """
    return "action_required" if status.startswith("awaiting_") else "summary"

_MESSAGES: dict[str, str] = {
    "awaiting_refine_input": "Kestrel needs your input refining {task}.",
    "awaiting_refine_approval": "PRD ready for review: {task}.",
    "done": "Change request opened for {task}.",
    "failed": "Workflow failed for {task}.",
    "escalated": "Autonomous run escalated — needs attention: {task}.",
}


def _is_notifiable(status: str) -> bool:
    return status in NOTIFY_STATUSES or status.startswith("awaiting_")


def _task_label(run: WorkflowRun) -> str:
    """The source-neutral ticket label for messages (feature 003)."""
    return run.task_ref or f"{run.repo}#{run.issue_number}"


def render_message(run: WorkflowRun) -> str:
    """
    Render the notification text for a run's current status.

    Source-neutral: rendered from the run's ``task_ref`` (``owner/name#123``
    for GitHub, ``RFC-123`` for Jira), so a Jira run — which has no numeric
    issue number — reads correctly.

    :param run: The run that just transitioned.
    :returns: A human-readable, ticket-scoped message.
    """
    template = _MESSAGES.get(
        run.status, "Kestrel needs your attention: {task}."
    )
    return template.format(task=_task_label(run))


@dataclass
class Notification:
    """A recorded notification for the in-app notification center."""

    id: int
    workflow_id: str
    repo: str
    #: GitHub issue number; ``None`` for a Jira-sourced run (feature 003).
    issue_number: int | None
    status: str
    message: str
    created_at: datetime
    read: bool


class Notifier(Protocol):
    """Notifies the user about a workflow run needing attention."""

    def notify(self, run: WorkflowRun) -> None:
        """Record a notification for the run's status, if any."""
        ...


def gate_deep_link(public_base_url: str, run_id: str) -> str:
    """
    Build a stable deep-link to a run's gate form, or "" when disabled.

    :param public_base_url: Configured public UI base URL; empty ⇒ no link.
    :param run_id: The durable run id (stable across restarts).
    :returns: ``{base}/?run={id}`` or ``""`` when no base URL is set.
    """
    if not public_base_url:
        return ""
    return f"{public_base_url.rstrip('/')}/?run={run_id}"


class InAppNotifier:
    """Persists a notification row for the in-app notification center."""

    def __init__(
        self,
        store: "NotificationStore",
        bus: "NotificationBus | None" = None,
    ) -> None:
        self._store = store
        self._bus = bus

    def notify(self, run: WorkflowRun) -> None:
        """
        Record a notification if the run's status warrants one.

        :param run: The run that just transitioned.
        """
        if not _is_notifiable(run.status):
            return
        self._store.add(
            workflow_id=run.id,
            repo=run.repo,
            issue_number=run.issue_number,
            status=run.status,
            message=render_message(run),
        )
        if self._bus is not None:
            self._bus.publish()


class TaskSourceNotifier:
    """Posts a thin comment on a run's originating ticket when it hits a gate.

    Source-dispatching (feature 003): the comment goes to *this run's* ticket
    via that source's ``TaskSource.post_comment`` — a Jira RFC for a Jira run,
    a GitHub issue for a GitHub run. Only ``awaiting_*`` gates and terminal
    ``escalated`` runs are posted (an escalation needs the human's attention on
    the ticket); other terminal outcomes are left to the in-app notifier.
    Posting is fire-and-forget so an outage never blocks the run (FR-028); the
    body is a fixed template plus an optional deep-link, never deliverable
    content (FR-029).

    :param sources: ``run.source`` -> ``TaskSource``. A run whose source is
        not present is skipped (e.g. a manual run with no external ticket).
    """

    def __init__(
        self, sources: "dict[str, object]", public_base_url: str = ""
    ) -> None:
        self._sources = sources
        self._public_base_url = public_base_url
        #: Keep fire-and-forget tasks referenced so they are not GC'd.
        self._tasks: set[asyncio.Task] = set()

    def notify(self, run: WorkflowRun) -> None:
        """Schedule a thin ticket comment for a gate / escalation."""
        gate = run.status.startswith("awaiting_") or run.status == "escalated"
        if not gate:
            return
        source = self._sources.get(run.source)
        if source is None or not run.task_ref:
            return
        body = render_message(run)
        link = gate_deep_link(self._public_base_url, run.id)
        if link:
            body = f"{body}\n\nOpen in kestrel: {link}"
        try:
            loop = asyncio.get_running_loop()
        except RuntimeError:
            _log.warning(
                "no running loop; skipping gate comment for %s", run.id
            )
            return
        task = loop.create_task(self._post(source, run.task_ref, body))
        self._tasks.add(task)
        task.add_done_callback(self._tasks.discard)

    async def _post(self, source: object, task_ref: str, body: str) -> None:
        try:
            await source.post_comment(task_ref, body)
        except Exception:  # noqa: BLE001 — best-effort; in-app is the fallback
            _log.exception("failed to post gate comment for %s", task_ref)


class CompositeNotifier:
    """Fans a notification out to several notifiers, isolating failures."""

    def __init__(self, notifiers: list[Notifier]) -> None:
        self._notifiers = list(notifiers)

    def notify(self, run: WorkflowRun) -> None:
        """Notify each child; one child's failure never stops the others."""
        for notifier in self._notifiers:
            try:
                notifier.notify(run)
            except Exception:  # noqa: BLE001 — isolate a misbehaving notifier
                _log.exception("notifier %r failed", notifier)
