"""Notifier protocol and in-app back-end for workflow attention
events.

Kept LLM-free and deterministic: messages are rendered from a
fixed per-status template, never generated by a model.
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import TYPE_CHECKING, Literal, Protocol

from app.models_workflow import WorkflowRun

if TYPE_CHECKING:
    from app.persistence.notification_store import NotificationStore
    from app.storage.notification_bus import NotificationBus

#: Statuses that warrant a notification: the human's attention is
#: needed (any "awaiting_*" gate) or the run reached a terminal
#: outcome worth knowing about. "rejected" is excluded — the human
#: caused it themselves by rejecting with no feedback.
NOTIFY_STATUSES = frozenset({"done", "failed"})

#: A notification's signal class (see module-notification-alarm-discipline).
#: An ``action_required`` item is a gate blocking on the human; a ``summary``
#: is a terminal, catch-up item that needs no action. The UI separates them
#: so a badge count means "things needing action", not "unread everything".
SignalClass = Literal["action_required", "summary"]


def signal_class(status: str) -> SignalClass:
    """
    Classify a notification status as action-required or summary.

    :param status: The run status the notification was raised for.
    :returns: ``"action_required"`` for an ``awaiting_*`` gate, else
        ``"summary"`` (terminal outcomes such as ``done``/``failed``).
    """
    return "action_required" if status.startswith("awaiting_") else "summary"

_MESSAGES: dict[str, str] = {
    "awaiting_refine_input": (
        "Kestrel needs your input refining {repo}#{issue_number}."
    ),
    "awaiting_refine_approval": (
        "Refined description ready for review: {repo}#{issue_number}."
    ),
    "awaiting_plan_approval": (
        "Implementation plan ready for review: {repo}#{issue_number}."
    ),
    "awaiting_implement_input": (
        "Kestrel needs your input during implementation: "
        "{repo}#{issue_number}."
    ),
    "awaiting_implement_approval": (
        "Implementation ready for review: {repo}#{issue_number}."
    ),
    "done": "PR opened for {repo}#{issue_number}.",
    "failed": "Workflow failed for {repo}#{issue_number}.",
}


def _is_notifiable(status: str) -> bool:
    return status in NOTIFY_STATUSES or status.startswith("awaiting_")


def render_message(run: WorkflowRun) -> str:
    """
    Render the notification text for a run's current status.

    :param run: The run that just transitioned.
    :returns: A human-readable, repo-scoped message.
    """
    template = _MESSAGES.get(
        run.status,
        "Kestrel needs your attention: {repo}#{issue_number}.",
    )
    return template.format(repo=run.repo, issue_number=run.issue_number)


@dataclass
class Notification:
    """A recorded notification for the in-app notification center."""

    id: int
    workflow_id: str
    repo: str
    issue_number: int
    status: str
    message: str
    created_at: datetime
    read: bool


class Notifier(Protocol):
    """Notifies the user about a workflow run needing attention."""

    def notify(self, run: WorkflowRun) -> None:
        """Record a notification for the run's status, if any."""
        ...


class InAppNotifier:
    """Persists a notification row for the in-app notification center."""

    def __init__(
        self,
        store: "NotificationStore",
        bus: "NotificationBus | None" = None,
    ) -> None:
        self._store = store
        self._bus = bus

    def notify(self, run: WorkflowRun) -> None:
        """
        Record a notification if the run's status warrants one.

        :param run: The run that just transitioned.
        """
        if not _is_notifiable(run.status):
            return
        self._store.add(
            workflow_id=run.id,
            repo=run.repo,
            issue_number=run.issue_number,
            status=run.status,
            message=render_message(run),
        )
        if self._bus is not None:
            self._bus.publish()
